### ISSUE TITLE
How do I send messages directly to a user?

### ISSUE THREAD

**Issue by shadow7412** [skoczen/will#108]
I have Will automatically parsing our build results.
Our build system automatically duplicates the tests to run on each individual branch - but I don't want to spam rooms with messages for branches only one or two users are working on.

So i want to be able to get users to 'subscribe' to branch build results - and have Will PM the result directly the interested users.

Does Will currently support this? If so, how?

**Comment by skoczen** [comment]
Hey @shadow7412 ,

You can definitely send direct messages to users.  However, the 'subscribe' functionality you describe would be custom code you'd write yourself.

To send 1-1 messages, you'll want to use `self.send_direct_message(hipchat_id, content, **kwargs)`.

It isn't currently part of the publicly exposed API (typical use-cases have involved will replying to 1-1 messages, instead of proactively sending them), but I'm open to it becoming publicly exposed.

If you're interested in writing that feature, let me know, and we can spec it out!

The interface would be something like:

```python
self.send_private_message(user, content, html=False, color="green", notify=False)
```

Thanks,
-Steven

**Comment by shadow7412** [comment]
I can give it a whirl.... But first I"ll barrage you with a few questions.

First thing I notice in the example interface is that PMs don't support colour - did we want to support it in case they add this in the future? Or should we leave it out?

The other one is most of the api is made from short one word functions... so I feel this should be the same.

Something like;
```self.whisper(user, content, **kwargs)```

What would ```user``` be? I assume by it's naming you would prefer something other than the raw hipchat_id?

**Comment by shadow7412** [comment]
I just had a bit of a play - and have come to realise that you were referring to a function that already exists.

```self.send_direct_message(hipchat_id, "Hi there")``` does basically exactly what I wanted, using the hipchat_id found in ```message.sender["hipchat_id"]```.

While it could be worth wrapping this a little more nicely, it doesn't look like there is any real functionality to be gained (except for perhaps referencing users by their name instead of hipchat_id).

**Comment by skoczen** [comment]
Hey @shadow7412 , 

I'm just tidying up issues - since it's been a while since I've heard on this one, and it looks like it's resolved, I'm closing it up.

If you're still having trouble, please re-open with the details!

Thanks,
Steven
