### ISSUE TITLE
Best place to put startup commands?

### ISSUE THREAD

**Issue by brandonsturgeon** [skoczen/will#177]
I have a few things I want to do when Jarvis starts up, but only need to run them once. For example, I have some database keys that I want to reset on startup.

`self.save("is_checking_sites", False)`

Where is the best place to put these?

**Comment by skoczen** [comment]
Hey @brandonsturgeon ,

Not ignoring it, just giving it some thought.  There isn't a *proper* place, because startup is expected to happen at random times, and nothing is predicted on it.

In short, there's no pattern in place for hooking into startup.

You could either just run it on module init (tracking in memory if it's run before), or in a module, and store whether it's run in storage.

Can you provide more context?  Maybe I can figure something else out!

**Comment by brandonsturgeon** [comment]
For example, I have a lot of sites I want to check uptime on. Some of them respond pretty slowly, so I have to set my timeout to ~10 seconds.

Now, a 10 second timeout for say, 15 sites, that's a 150 second job at worst. But say I want to check every 60 seconds (Because each site COULD only take 1 second, making a 15 second job.)

I can't be checking the sites with TWO jobs at the same time, so I need a DB entry that will keep track of if it's checking the sites right now. (is_checking_sites)

```
@periodic(minute='0-59/2')
def check_sites(self):
    check = self.load("is_checking_sites", False)
    if check is False:
        return False
    self.save("is_checking_sites", True)
    for site in sites:
        self._check_site(site)
```
Now if Will is restarted in the middle of the job, "is_checking_sites" is stuck as False and will have to manually be cleared.

I want him to be able to reset "is_checking_sites" to False when Will is started.

I was thinking about somehow having Redis expire the key after X seconds, but that seems kind of flaky and imperfect. I'd like to save that as a sort of last resort.


Thanks for the reply @skoczen !

**Comment by skoczen** [comment]
Hey @brandonsturgeon,

So uptime in specific, I'd consider either pagerduty (which will has pretty awesome built-in-support), or re-architecting.

I use will to monitor uptime on ~20 sites, but keep each one as a separate task, so the locking stuff isn't necessary.  It's also possible you could re-arch your site check so nothing bad happens if you check two sites concurrently.

But- as to the use-case for resetting the variables on start (assuming your example was just an example), hmm.

I've been thinking about this for the past 10 minutes, and I don't have much better than running the reset on a module import, and storing that it's been run in ram.  It won't be perfect, but it'd be a solid way to get the run-once behavior.

If it were me though, I'd re-architect the problem so it wasn't necessary.  Will's built around the expectation that restarts are random, and downtime will occur.  With those assumptions, it'd be more aligned to make your task be able to be killed without side effects, rather than trying to handle them.

Does that help?

**Comment by brandonsturgeon** [comment]
Hey @skoczen 

Sorry I put off responding. I did rework the problem so a run-once kind of behavior wasn't required. I went ahead and made the site checks a threaded process. It always completes quick enough now that I don't have to worry about overlaps.

Thanks for the advice!

**Comment by skoczen** [comment]
Hey @brandonsturgeon , no worries - glad to hear it's all working!
