### ISSUE TITLE
Import plugins from other plugins?

### ISSUE THREAD

**Issue by brandonsturgeon** [skoczen/will#178]
Is it possible to import another plugin from a plugin?

* plugins/
    * helper_plugin.py
    * job_plugin.py

```
#helper_plugin.py
from will.plugin import WillPlugin
from will.decorators import respond_to, periodic, hear, randomly, route, rendered_template, require_settings
import random

class HelperPlugin(WillPlugin):
    def generate_number(self):
        return random.randint(0,100)
```

```
#job_plugin.py
from will.plugin import WillPlugin
from will.decorators import respond_to, periodic, hear, randomly, route, rendered_template, require_settings
from helper_plugin import HelperPlugin

class JobPlugin(WillPlugin):
    def do_job(self):
        print "Random number is {}".format(HelperPlugin.generate_number())
```

This is an example of what I want. job_plugin fails on startup saying that there's no module named helper_plugin

**Comment by skoczen** [comment]
Yep, you can import just fine, you'll just have to make sure you get the import paths right.  In this case, there are likely multiple `plugins` modules, so try importing from either: 
- somewhere higher and clearer on the import path `my_will.plugins.helper_plugin`, or
- using a relative import `.helper_plugin import `

Let me know if that doesn't help out, and thanks again for your continued patience - hoping to have a sprint to address all the issues and PRs late this week!

**Comment by brandonsturgeon** [comment]
Not a problem! Using the heck out of Will here at the office. 

I tried both of those and neither of them seemed to work.

* `ImportError: No module named my_will.plugins.helper_plugin`

And using the second way..

`from .helper_plugin import HelperPlugin`
`ValueError: Attempted relative import in non-package`

**Comment by brandonsturgeon** [comment]
Alright! I've found something.

I have my entire will folder as a git repo.

To fix this issue of not being able to import anything, here's what I did that seems to work.

* Go into the plugins folder
* open python command line
* import helper_plugin
* exit()
* commit and push helper_plugin.pyc
* stop will, pull in changes, and start again

I think that fixed it, but I tried a lot of different things before getting to the end here. However you can generate the .pyc locally and then pushing it up is how I fixed it.

**Comment by skoczen** [comment]
Hey @brandonsturgeon , 

So, to confirm, you're committing `*.pyc` files in your git repo?  That's likely to be your problem.  They're arch-specific, and best practices is to make sure they're not being committed.

If you delete them all from your git repo (and locally), do you still have the problem?

If you're on a *nix, this should recursively kill 'em:

``bash
find . -iname "*.pyc" -delete
```

**Comment by brandonsturgeon** [comment]
Thanks for the reply, @skoczen 

I've completely removed all .pyc from the project and ran it fresh. I try to `import helper_plugin`at the top of one of my plugins but it fails saying no such module exists. There is definitely a `helper_plugin.py` in the plugins folder. I can run `python` in the plugins folder and `import helper_plugin` without any problems, though.

**Comment by skoczen** [comment]
@brandonsturgeon Ah, that makes more sense.

From an adjacent file (in the same folder), you'd want `import .helper_plugin`. 

Your other option is to fully-scope the import from a higher level on your python path.  Something like

```python
from my_will.plugins import helper_plugin
```

Does that help?

**Comment by brandonsturgeon** [comment]
@skoczen It was saying that `import .helper_plugin` was an invalid syntax.

I found elsewhere that you need to do `export PYTHONPATH=$PYTHONPATH:$PWD`.

I did that in the plugins folder, but then quickly did it again in the root will folder (next to `run_will.py`) and it seems to work again. Every time I get it to work, I can't seem to get a 100% solid reasoning behind it.

**Comment by skoczen** [comment]
Hey @brandonsturgeon ,

So - not that you're anything like me - but this exact sort of "what's going on??" magic in python confused me for a while.  Here's what cleared it up for me.  If this is all old hat to you, thanks for hearing me out - one never knows, and I put it out there just because it was so confusing to me all those years ago!

Open up a new python interpreter, then run:

```python
import sys
print sys.path
```

This is the total list of places python will look for a module, in order. The first one it finds is what it goes with - so if you have two `plugins` modules, the first one in the path is the only one that code can get to.

Note that the list is mutable - you can add new places to it, chop others out, all that.

We do some of that kind of magic when will starts up (see below), and it's not an uncommon pattern to see in python projects - it makes imports a lot simpler.

Will's path magic:
```python
PROJECT_ROOT = abspath(os.path.join(dirname(__file__)))
PLUGINS_ROOT = abspath(os.path.join(PROJECT_ROOT, "plugins"))
TEMPLATES_ROOT = abspath(os.path.join(PROJECT_ROOT, "templates"))
PROJECT_TEMPLATE_ROOT = abspath(os.path.join(os.getcwd(), "templates"))
sys.path.append(PROJECT_ROOT)
sys.path.append(os.path.join(PROJECT_ROOT, "will"))
```
The other point that caught me for a while was referencing the relative directories.

```__file__``` is where the physical file that contains that line of code lives.  Except in weird cases where you've dynamically created modules out of thin air (we also do some of this deep in will's innards, but it's a pretty rare thing - I've needed it twice in 8 years of python), it's a real path on the disk.

```os.getcwd()``` is the folder that the initial python interpreter was called from.  The working directory.

If you combine those two things with the sort of magic that will (and other libraries) are doing, you can get the maddening confusion that you're running into.  I spent several weeks *certain* that the core language had a bug.  It did not.  It behaves consistently.  It just allows for some magic, and paths really matter.

Hope that's helpful to you, and if not, feel free to toss more questions or details about your specific setup out there!

**Comment by brandonsturgeon** [comment]
@skoczen Thanks so much for the reply! I know you didn't have to go into such detail, and I really appreciate it.

I'm 19 years old, and I've been playing with python for just about 2 years now, so guidance like this is always super helpful (especially when it's a specific problem like this, not sure how I would have been able to understand it without some help)

Thanks again!

**Comment by skoczen** [comment]
@brandonsturgeon absolutely!   It's how we all learn.  You'll do the same for someone someday soon.
