### ISSUE TITLE
Username with dash '-' symbol gives error

### ISSUE THREAD

**Issue by chiel1980** [skoczen/will#196]
When running Will using a username as test-2@domain.com for hipchat, I receive the following error message (because of split function):
```
      ___/-\___
  ___|_________|___
     |         |
     |--O---O--|
     |         |
     |         |
     |  \___/  |
     |_________|

      Will: Hi!


Verifying environment...
  ✓ WILL_USERNAME
  ✓ WILL_PASSWORD
  ✓ WILL_V2_TOKEN
  ✓ WILL_REDIS_URL

Verifying credentials...
Traceback (most recent call last):
  File "./run_will.py", line 6, in <module>
    bot.bootstrap()
  File "/usr/local/lib/python2.7/dist-packages/will/main.py", line 100, in bootstrap
    self.verify_environment()
  File "/usr/local/lib/python2.7/dist-packages/will/main.py", line 221, in verify_environment
    user_id = settings.USERNAME.split('@')[0].split('_')[1]
IndexError: list index out of range
```
is this a bug or a feature? ;)
If so can we allow '-' symbols in usernames (since it is a valid email address and thus a valid Hipchat account) ?

Cheers,

Michiel

**Comment by skoczen** [comment]
Hey Michiel,  ( @chiel1980 for ping )

Thanks for reaching out.  The issue is actually that you're using the wrong email as the `WILL_USERNAME`.

It should be the jabber ID, and have a format like `123456_1324567@chat.hipchat.com`.

Take a look at the [screenshot here](http://skoczen.github.io/will/#get-will-running-locally) or re-run will without a USERNAME for details.

Best, and let me know if that doesn't work!

-Steven
