### ISSUE TITLE
High availability

### ISSUE THREAD

**Issue by ayashjorden** [skoczen/will#204]
Hi,
There's not other channel of communication.....:

What are the measures that one should take in order to run multiple Instances of Will on the same environment?

Can they share the same Redis? will they know which instance responses to @hear/@respond_to/OTHER?

Thank you,
Yarden

**Comment by woohgit** [comment]
I'm sure it's a bad idea to use the same redis.

What I'd do (and what I do) is run will from a docker container and set up correct monitoring for will.

If you have a proper monitoring, you can automate the recovery (restart a dead will).

if you really need to have a master/slave will, the slave will would need to monitor the master will and if it's down or not responding it can respond to @hear/@respond_to otherwise stay standby.

**Comment by brandonsturgeon** [comment]
@ayashjorden Were you able to find a good way to do this? Did the Docker solution appeal to you?

**Comment by ayashjorden** [comment]
Hi @brandonsturgeon,
We did setup proper monitoring and recovery using systemd.

Docker is not part of the stack so we didn't use it.

**Comment by skoczen** [comment]
Hey @ayashjorden , at present, will really isn't designed to run multiple instances on the same server.  That said, it should be possible - the things you'd want to look out for are:

1. Port conflicts
2. Redis DB/Storage backend conflicts.  You can use the same redis, but different instances - it's just threads connecting to a specific db, so there's no cross-knowledge present.
3. Env variable conflicts.

If you can sort those three, it should be doable!

Also, since the question was a year-plus ago, I'm closing this up, but please reopen if the question is still present for you!

**Comment by dsoprea** [comment]
@skoczen 

How do multiple instances coordinate who is going to respond? If anything, I'd assume that we can use Redis as a queue to serialize the events rather than a simple pub-sub that broadcasts all events to all instances. I'm surprised that this wasn't mentioned.

Since the suggestion has been made about reopening this and there's already a precedent for posting messages over the long-term and it's not clear if there is a path forward, I'm just posting the question here. If it developers into something more, we can create a new issue.
