### ISSUE TITLE
403, 'This action requires one of the following scopes: [u'view_group']'

### ISSUE THREAD

**Issue by YesThat** [skoczen/will#229]
Howdy.   

I'm seeing an issue where Will can validate that it has a good v2 token, but immediately hits a problem and 403s on view_group.   No matter the type of v2 token I give Will, I see the same issue.  I can set the token to a bad token and validate that it swaps to a 401, so I know the token itself is good.  (Which type of v2 token *should* I be using?  No mention of that in the docs)

I've set a WILL_v1_TOKEN as well with no change.

This is Will 0.9.3, running python 2.7.5 (system python on rhel 7, in a virtualenv.)
The hipchat server is our groupname.hipchat.com and bin/postactivate looks like:

> export WILL_USERNAME='`<id>@chat.hipchat.com`'
> export WILL_PASSWORD='`<password>`'
> export WILL_V1_TOKEN='`<v1 token>`'
> export WILL_V2_TOKEN='`<tried various v2 tokens of different access levels>`'

./run_will.py shows:
> Verifying environment...
>   ✓ WILL_USERNAME
>   ✓ WILL_PASSWORD
>   ✓ WILL_V2_TOKEN
>   ✓ WILL_REDIS_URL

> Verifying credentials...
> ERROR: We ran into trouble: 'This action requires one of the following scopes: [u'view_group']`

I added a few bits of additional logging to validate the user id as well as the returned error and don't really see why it's failing.   So my question is, how can I help you help me?  What info can I share?  Our group has over 1000 rooms and 5000+ users, so I have to wonder if whatever fix there was for using v1 vs v2 tokens works to this scale.

**Comment by pepedocs** [comment]
Hey, 

Firstly, double-check your postactivate script make sure you are setting the environment variables with correct value, for example your user name above does not have the user ID part and the rest of the variables are empty strings (unless you deliberately hiding these values here).  Don't rely on the v1 token AFAICT I don't think they are still being used anywhere. Again make sure the environment variables are set properly. 

The verification of the environment variables passed because it is only checking their values and not actually using it for the intended service. So a '' will pass because its a valid value but when it tries to connect to your server a '' is actually an invalid user name or etc.

**Comment by YesThat** [comment]
Odd, the variables must have been wiped out when I used ">" as a quote for the formatting here on github.  There are indeed valid entries in all of those variables.   The username is of the format 123456_78901234@chat.hipchat.com where the password works (I verify this by manually copy and pasting those vars in to a hipchat session and seeing them auth.

Which *type* of v2 token should I be using there?  I see various v2 types of tokens, view group, administer group, etc, etc.

**Comment by YesThat** [comment]
Hrrm.   Seems there was definitely pebcak at play here.  Manually exporting the vars seems to have allowed a connection.  Closing the issue.
