### ISSUE TITLE
Will integration with Hipchat

### ISSUE THREAD

**Issue by Manasvibhatt297** [skoczen/will#263]
I followed the steps you mentioned on the website but will is unresponsive in hipchat..please guide me through this...this is urgent

**Comment by Manasvibhatt297** [comment]
Loading configuration...
  Importing config.py... 
    ✓ Valid.
  Verifying settings... 
    ! Warning: no ROOMS list found in the environment or config.  This is ok - Will will just join all available rooms.
    - Note: WILL_REDIS_URL not set.  Defaulting to redis://localhost:6379/7.
    - Note: REDIS_MAX_CONNECTIONS not set. Defaulting to 4.
    ! Warning: no PUBLIC_URL found in the environment or config.  Defaulting to 'http://localhost:5222'.
    ! Warning: no V1_TOKEN found in the environment or config.This is generally ok, but if you have more than 30 rooms, you may recieve rate-limit errors without one.

are these kind of warning ok?

**Comment by Manasvibhatt297** [comment]
is my postactive file correct?
is there something more i need to add?

`_export WILL_USERNAME=************@chat.hipchat.com
export WILL_PASSWORD=*******
export WILL_V2_TOKEN=******************_`

**Comment by Manasvibhatt297** [comment]
what is meant by public url?
what is redis_server exactly doing?

**Comment by skoczen** [comment]
@Manasvibhatt297 just a quick note on some etiquette and suggestions.

As I'm sure you know, everyone here is working on will in their free time, in addition to their regular work and such.  Because of that, it's not possible for folks to respond right away.  It's also considered pretty rude to re-post the same issue in multiple places, and directly ping unrelated people.  We're all stretched and stressed, and saying that it's urgent is more likely to make folks look away than stop to help.

Broadly, here's the kind of request and/or bug report that is going to get you the best responses, both here and everywhere across the internet.

1. **Clearly document your complete configuration**, what you've done, and how you got to this point.
2. **Document your problem**, including both what you see happening, and what you expect to be happening.  By the end of steps 1 and 2, anyone who comes across your issue should be able to reproduce it without talking to you.
3. **Do your homework, and communicate that**.  Open-source code is different than off-the-shelf stuff in that you can read the code and understand what's happening.  For a lot of us, this process of figuring out what was going wrong in our setup is a big part of how we learned to code in the first place.  
At the least, showing that you're looking through a package, have googled everything you can, and have made a serious effort will help your chances that someone will take the time to get things fixed.  The more lifting you do, the less it puts on the stranger who's helping you. The easier you can make it for them, the more likely they are to help.
4. **Spend time on formatting**.  This follows the above point, but specific to how you document and communicate your issue.  Take a bit of time to understand github markdown, put your code and output in styled fences, and edit your issues to clearly communicate the above, instead of adding a ton of comments. Include the configuration, what steps were taken, what was supposed to happen, and what did.
5. **Be kind.**  It's the [core principle](http://skoczen.github.io/will/improve/#our-culture) of our culture, and it holds up across the internet.  Appreciate that people are spending the time they could be spending with their families and friends to help out strangers on the internet, and make something useful.  Showing a little appreciation and acknowledgement goes a long way.
6. **Be patient.**  Everyone is busy, and we're all triaging to see stuff we can fit into tiny windows of time throughout our days.   If there's an issue that has 1-5 covered, it's more likely to get attention sooner - but even if not, generally, someone will get to it eventually.  Hang in there.

In this case, I got and replied to your first issue, didn't see any of 1-5 done there, and back-burnered it.  You responded by opening a second issue, and commenting on another closed issue and pinging several people who weren't involved.  None of those things are helping you get an answer sooner, and they're making extra work  (and hurting your reputation) along the way.

My guess, not knowing you, is that you're pretty new to github and maybe development.  That's cool - we've all been there.   I'd recommend you read around on [stack overflow](https://stackoverflow.com/questions/30486628/adding-issue-to-github-what-is-etiquette) or similar sites to understand the cultural conventions for sites like github, and open-source projects in general.  It's learning that will serve you well, throughout your journey.

Finally, on your actual issue, I'm keeping this issue open, closing your extra ones, and redirecting the other pings you've made here. 

I understand that your will isn't responding.  There are also thousands of people using will successfully, so it's very likely that the problem is in your setup.

Please document your setup (OS, python version, pip libraries installed, which variables you're setting in your virtualenv, which you're setting in `config.py`, and any steps to reproduce, and things you've already tried in getting it fixed.)  Do 1-4 on this issue, and it's going to make it much, much faster to get whatever you're running into resolved.

Thanks for listening, and for being a part of the will community!
