### ISSUE TITLE
Programmer help no longer works

### ISSUE THREAD

**Issue by acommasplice** [skoczen/will#323]
Not sure when this broke (looks like it was working in 2.0.1b2, def not working in 2.1.0), but it looks like main.py doesn't save the "all_listener_regexes" list anywhere so "programmer help" generates a TypeError: 'NoneType' object is not iterable.

Adding a 

`self.save("all_listener_regexes", self.all_listener_regexes)`

before the last line of main.py fixed it for me.

**Comment by skoczen** [comment]
Hey @acommasplice , thanks for the report!  First glance - this looks like a great catch, and fix.  Would you mind putting in a PR?

Note that it may be a couple weeks before I can get it in (see #324), but it'll get there!  Thanks the report, and for making Will better and better. :)

**Comment by acommasplice** [comment]
@skoczen done! See https://github.com/skoczen/will/pull/325

**Comment by skoczen** [comment]
(Quick paste-on-all-open-issues update:)

**TL;DR**: New Will release EOM. Also, you're awesome.

**Full Update:** This may be TMI for you, and if so, cool, the thing you probably care about is above.  But given the total radio silence on my part - and the fact that I've always tried to create a community here where we got to be actual people instead of avatars and PRs, I wanted to give a bit more context.

As you may be aware from an earlier AFK, I got married in December, which was great, but burned the month from a Will perspective.  I planned to get back on it at the start of January, but instead found myself selling our house, and simultaneously hit with a surprisingly severe bout of depression.  The time since Jan 1 has been sort of a blur.  A dark blur, but a blur more than anything.   I saw the PRs and comments coming in, but didn't have the energy or time to do anything about them.

Things seem to be clearing up on both counts now, and I'm _really_ looking forward to getting these fixes in, catching up on bug reports, and being active in improving Will again. :)

With that, I'm aiming to get all outstanding PRs bundled into a release, and all issues replied to by the end of February.

Most of all, thanks for your contribution to Will, your patience with an imperfect, quite human project maintainer, and for continuing to come back, engage, and spend some of the precious seconds you get on earth making this project better.

I appreciate you.  Thank you.

**Comment by skoczen** [comment]
This has been fixed, and released in 2.1.1!
