### ISSUE TITLE
Will doesn't respect slack threads when giving "unknown" responses

### ISSUE THREAD

**Issue by netjunki** [skoczen/will#332]
<img width="1065" alt="genericresponse_threadbug" src="https://user-images.githubusercontent.com/64289/35308414-7a611186-005c-11e8-8511-48fce5164a7e.PNG">

Will's generic unknown command responses don't show up in the thread where the command was attempted.

**Comment by skoczen** [comment]
(Quick paste-on-all-open-issues update:)

**TL;DR**: New Will release EOM. Also, you're awesome.

**Full Update:** This may be TMI for you, and if so, cool, the thing you probably care about is above.  But given the total radio silence on my part - and the fact that I've always tried to create a community here where we got to be actual people instead of avatars and PRs, I wanted to give a bit more context.

As you may be aware from an earlier AFK, I got married in December, which was great, but burned the month from a Will perspective.  I planned to get back on it at the start of January, but instead found myself selling our house, and simultaneously hit with a surprisingly severe bout of depression.  The time since Jan 1 has been sort of a blur.  A dark blur, but a blur more than anything.   I saw the PRs and comments coming in, but didn't have the energy or time to do anything about them.

Things seem to be clearing up on both counts now, and I'm _really_ looking forward to getting these fixes in, catching up on bug reports, and being active in improving Will again. :)

With that, I'm aiming to get all outstanding PRs bundled into a release, and all issues replied to by the end of February.

Most of all, thanks for your contribution to Will, your patience with an imperfect, quite human project maintainer, and for continuing to come back, engage, and spend some of the precious seconds you get on earth making this project better.

I appreciate you.  Thank you.

**Comment by skoczen** [comment]
@netjunki thanks for this - I was pretty sure I'd covered that case, but will look into it!

For clarity, this is:
1. We're in a threaded conversation, off a (room?  1-1?)
2. We directly mention Will with a command he doesn't understand.

He then replies in the main room, where he should reply in the thread.

**Comment by netjunki** [comment]
1. That's in a room... let's me check really quick if this happens 1-1. Yeah it happens 1-1

so you're understanding is correct.

**Comment by skoczen** [comment]
Great, thanks for the double-check!

**Comment by skoczen** [comment]
This has been fixed, and released in 2.1.1!

**Comment by netjunki** [comment]
Verified fixed on our production server as well. Thanks!

**Comment by skoczen** [comment]
Fantastic- thanks, @netjunki !
