### ISSUE TITLE
Getting Error when somebody messages my bot

### ISSUE THREAD

**Issue by laysz** [skoczen/will#336]
So I get all successes and I can successfully chat with will in the terminal:

Verifying IO backends...
  ✓ HipChat
    ✓ HIPCHAT_USERNAME
    ✓ HIPCHAT_PASSWORD
    ✓ HIPCHAT_V2_TOKEN
  ✓ Interactive Shell

Bootstrapping complete.

Starting core processes:
  ✓ IO: HipChat Backend started.
  ✓ IO: Interactive Shell Backend started.
  ✓ Analysis: NoAnalysis Backend started.
  ✓ Analysis: HistoryAnalysis Backend started.
  ✓ Generation: FuzzyAllMatchesBackend Backend started.
  ✓ Generation: RegexBackend Backend started.
  ✓ Web server started at http://localhost:80.
  ✓ Scheduler started.

But when somebody sends a message to me, I get:

You:  Thu, 15 Feb 2018 14:32:10 [ERROR] Socket Error #54: Connection reset by peer
Thu, 15 Feb 2018 14:34:38 [CRITICAL] Error handling incoming event {'body': 'Hi', **'xmpp_jid': u'30167_lester@conf.hipchat.com',** 'from': '30167_lester@conf.hipchat.com/Harish Kumar S (cybage)', 'parent': None, '_index': 0, 'from_jid': '30167_2170928@chat.hipchat.com', 'loaded_plugins': set([]), 'namespace': u'jabber:client', 'mid': '99ef0b56-a5e7-4f85-b21c-842688ca3af0', 'ts': '1518672877.977057', 'to': '30167_1982453@chat.hipchat.com/bot||proxy|pubproxy-d600.hipchat.com|5282', 'tag': u'{jabber:client}message', 'plugins': OrderedDict(), 'iterables': [], 'type': 'groupchat'}: 
Traceback (most recent call last):
  File "/Users/lie.xie/will/chatbot/lib/python2.7/site-packages/will/backends/io_adapters/base.py", line 43, in handle_incoming_event
    m = self.normalize_incoming_event(event)
  File "/Users/lie.xie/will/chatbot/lib/python2.7/site-packages/will/backends/io_adapters/hipchat.py", line 629, in normalize_incoming_event
    **channel = clean_for_pickling(self.channels[event["xmpp_jid"]])
KeyError: u'30167_lester@conf.hipchat.com'**

The clean_for_picking does not seem to like my key 30167_lester@conf.hipchat.com. That seems to the name internal name of my channel. Please assist.

Thanks!

**Comment by skoczen** [comment]
(Quick paste-on-all-open-issues update:)

**TL;DR**: New Will release EOM. Also, you're awesome.

**Full Update:** This may be TMI for you, and if so, cool, the thing you probably care about is above.  But given the total radio silence on my part - and the fact that I've always tried to create a community here where we got to be actual people instead of avatars and PRs, I wanted to give a bit more context.

As you may be aware from an earlier AFK, I got married in December, which was great, but burned the month from a Will perspective.  I planned to get back on it at the start of January, but instead found myself selling our house, and simultaneously hit with a surprisingly severe bout of depression.  The time since Jan 1 has been sort of a blur.  A dark blur, but a blur more than anything.   I saw the PRs and comments coming in, but didn't have the energy or time to do anything about them.

Things seem to be clearing up on both counts now, and I'm _really_ looking forward to getting these fixes in, catching up on bug reports, and being active in improving Will again. :)

With that, I'm aiming to get all outstanding PRs bundled into a release, and all issues replied to by the end of February.

Most of all, thanks for your contribution to Will, your patience with an imperfect, quite human project maintainer, and for continuing to come back, engage, and spend some of the precious seconds you get on earth making this project better.

I appreciate you.  Thank you.

**Comment by laysz** [comment]
Hello @skoczen 

Thanks for your reply. Totally understand your situation. Will looks like a great tool that can benefit many people. Take it easy man :)

Cheers

**Comment by laysz** [comment]
@ostracon fix worked for me. Thanks a lot bud!
