### ISSUE TITLE
Slack Events API

### ISSUE THREAD

**Issue by pastorhudson** [skoczen/will#381]
I would like to be able to answer from the Slack Events API. So I can have will working with multiple slack teams. Does anybody have this working? Is there broader interest in this?

**Comment by BrianGallew** [comment]
This is included in the new Slack backend (currently under review).  However, there are no handlers in place for any events other than [open, channel_added, user_changed, message].  Handlers for other events would have to be created and then somehow exposed.  That last part is difficult because it's very Slack-specific.

**Comment by Ashex** [comment]
I'm linking this to the PR @BrianGallew mentioned. If we want to handle additional events we can get that done but let's consider it a separate enhancement.
