### ISSUE TITLE
Slack APIs consumed by will are slated to be shut off in Feburary 2021

### ISSUE THREAD

**Issue by dpritchett** [skoczen/will#426]
_As seen on [Slack's API changelog](https://api.slack.com/changelog)_

> Beginning June 10th, 2020, all newly created Slack apps will be unable to use the deprecated methods in channels.*, im.*, mpim.*, and groups.*. Existing apps have until February 24th, 2021 to migrate to the [Conversations API](https://api.slack.com/docs/conversations-api). [Learn more](https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api).

A quick peek at [`will.backends.io_adapters.slack`](https://github.com/skoczen/will/blob/master/will/backends/io_adapters/slack.py#L22-L24) shows that we do in fact use the methods slated to be shut off.

I'd recommend a new slack adapter v2 as a sibling to the existing slack adapter. It could work as a python package or as a direct PR into `will`.

**Comment by dpritchett** [comment]
Tag @briangallew for a heads up

**Comment by pastorhudson** [comment]
@Ashex @skoczen any thoughts on this? Is this the end? Or is there an appetite to write new slack backend?

**Comment by BrianGallew** [comment]
Given the complete lack of activity my team at work forked will and wrote a
new Slack backend.  It's not terribly difficult.  The biggest problems were:
1) having to manage the room/user lists
2) changes in structures returned by the Slack API.

Took me about 2 days to get the bulk of the changes in place, and another
couple day's worth of bug fixing.
As a team we've elected to NOT make our fork public as it's pretty clear
will is dead and we're really not feeling positive about supporting this
for the public.

**Comment by Ashex** [comment]
I'm afraid I won't be able to make any contributions in the near future so this project may be put on ice as a result. Having worked with the slack backend it's been in a half-baked state for some time _but_ reworking it to the latest API is doable, it's just going to require serious commitment to refactor and write the associated tests.

**Comment by BrianGallew** [comment]
Not really.  I've already *done* it.  Took me 3 days to learn the existing
code and make the required changes.  I didn't extend the tests at all, but
the existing ones continue to work.  We've been running our fork in
production for almost 2 months now.  The real issue is the complete lack of
progress from the committers: no issue review, no PR merging/rejection,
commits, or really any evidence that the project is not stone dead.

**Comment by Ashex** [comment]
I had taken it that we'd have to do a separate rewrite since you had elected to not make your fork public. You've seen the other issues discussing where to take the project in which no consensus was ever reached (primarily not wanting to drop support for python 2.7). I would like to see the project come back in some form but we'd need to settle on a roadmap of features/improvements so that we can tackle them even when the contributors availability is limited. 

I do feel some level of responsibility to get this project moving again so if we do have developers interested in contributing we can determine what to fix (priority #1 being the slack api) and get started, I'm not able to be super active as the bulk of my work these days is audit related (and there's a bit of irony in that). This of course may involve a full fork of the project so we have full access as I and a few other individuals only have contributor access with the owner being largely absent from the project.

**Comment by pastorhudson** [comment]
@BrianGallew Would you be willing to make your backend public? Did you have to change many other things or just will/backends/io_adapters/slack.py ?  Even if it's a gist? I'd like to get my fork running, and would love to jump off of your slack.py.

**Comment by BrianGallew** [comment]
Let me see how much hassle it's going to be with legal

**Comment by skoczen** [comment]
@BrianGallew if you're willing or able to share that work, that'd be tremendous.  Over the years (8 of them now!), the community has done the bulk of the support on this project, so I don't think your team sharing code to a project that's benefitted you all over the years puts any onus for support on you - it just makes other folks lives easier, and if anything, might even get you some upstream bugfixes down the road.  

Not to put too fine a point on it, but nobody's Will would have worked for all these years without the contributions of everyone here.  So if there's a way it can be done, that'd be lovely.

That said -- I know legal's gonna legal.  (And it might be too late for the ask questions later approach.)

If that's the case, as Brian alluded to, V2 of Will was specifically designed to make adding or replacing a backend easy, as it came out of hipchat's sudden collapse - there's just a handful of methods that need built out.  (Take a look at [the shell backend](https://github.com/skoczen/will/blob/master/will/backends/io_adapters/shell.py) for an example of this.)   Brian, if legal's not on board, if you'd be willing to paste links to the relevant parts of the slack docs / SDKs or toss up some pseudocode, and mention bugs and workarounds you ran into, it sure would make the implementation job easier.


**On the broader issues of Will, and whether the project is dead -** 
I think an open source project is dead if one of two things is true:

1) Nobody is working on it anymore. Some projects hit maturity and see significant drop-offs in code additions; it doesn't mean they're dead.  From this thread, it seems like folks are still interested in keeping it going, so I'm going to assume we're still good there.

2) There's bureaucracy, cruft, or blocks in the way of new releases, or nobody's sure who's running things.  This sounds like it might be the case.

About two years ago, there was a [long discussion](https://github.com/skoczen/will/issues/395#issuecomment-461092630) about the future of Will.  TL;DR, I recognized that I didn't have time for Will (it's been a project of love since ~2015), wasn't coding full-time for work anymore, and handed the reins over to the folks who were most active at the time, @Ashex, @chillipeper , @rsalmond , and @wontonst  .

It seems like there's still friction on this, so if there are other ownership or changes that need to be made, we need to move will to an org repo, whatever it is, I'm happy to do it.

**Most of all**, I hope all of you are staying well, hanging in there, and I'm glad to hear from you, and see your voices after all we've all been through in the past year. 

I'm in a van on a distant coast of New Zealand on pretty shoddy internet at the moment - so if I don't reply to this thread immediately, please be patient.  I'll for sure reply, and get the repo and access sorted out to whatever folks here decide.

Be well,
-Steven

**Comment by BrianGallew** [comment]
So, the good news is that Legal has approved a new contribution process.
The bad news is that while I'll happily contribute my work back, there's no
way it's going to happen in less than two weeks, and more likely three.
There are also the complications that my fork now has significant changes
not strictly related to the Slack backend update.  It'll take me some work
to split up my efforts into targetted chunks.

**Comment by skoczen** [comment]
@BrianGallew that's fantastic news.  Given how long we've all had to solve this, late is definitely better than never.  

Thanks for jumping through the hoops, and being willing to share it back.

Are there access issues I can solve?  Do we need other people as repo collabs / pypi release owners?

**Comment by BrianGallew** [comment]
At this point the only issue is just making sure we get review/merge in a
reasonable time frame, and in the end it's still waiting for me to get the
PR approved and set up.

**Comment by Ashex** [comment]
@skoczen I don't think anyone has pypi access, can you grant it to me?

@BrianGallew you can tag me in the PR when you submit it and I'll review immediately.

**Comment by BrianGallew** [comment]
Thanks.  I've got a PR in the approval process at work right now.  I need another senior engineer to vet it, and a quick (!) signoff from Legal.   With any kind of luck that will happen by COB Monday and I can then submit it here.

**Comment by BrianGallew** [comment]
Legal approved!
