### ISSUE TITLE
Doing work in a plugin __init_() hangs startup

### ISSUE THREAD

**Issue by amckinley** [skoczen/will#58]
With this code:
````
class H5Handoff(WillPlugin):
    def __init__(self):
        self.h5s_heard = []
         r = redis.Redis()
        try:
            res = json.loads(r.get("current_sre_oncall"))
            self.current = res
        except Exception as e:
            logger.warning("failed to fetch oncall: %s", e)
            return None
````

Will never starts up, or even begins writing to redis for the scheduler lock. It hangs after print this to the console:
````
Starting core processes
  ✓ Web server started.
  ✓ Scheduler started.
````
Removing the redis call makes it startup cleanly again. Moving this code into a different method and invoking it after startup via @hear works fine. I'm not sure if it's because I'm talking to redis, doing I/O in general, or what.

**Comment by wohali** [comment]
Hey @skoczen I can't re-open this issue, so I thought I'd leave some analysis here. In short, your mixing of gevent and multiprocessing is going to keep biting you in the rear. I attempted to monkeypatch with (socket=False), but then the bottle gevent server hangs on a socket.recv() as it can never know that data comes back.

The quickest solution is to use cherrypy for the bottle server instead of gevent. (Any other wsgi container would work, e.g. gunicorn. If I had the time, I'd probably make a PR to drop bottle for Flask.) 

Here's a [quick diff](https://gist.github.com/wohali/4097f09002ad36798be3) that fixed things, as I don't feel like forking tonight. Also, using something other than gevent will let you reload bottle, which could be nice for dynamic reconfiguration without fully restarting will. :wink: 

My guess is that, with this, you can possibly back out some of your multiprocessing DNS work as well, though multiprocessing.Queue is typically a good option anyway.

References with some additional detail: [1](http://stackoverflow.com/questions/8678307/gevent-monkeypatching-breaking-multiprocessing), [2](http://stackoverflow.com/questions/16517796/bottle-gevent-and-threading-gevent-is-only-usable-from-a-single-thread), [3](http://stackoverflow.com/questions/13318608/streaming-connection-using-python-bottle-multiprocessing-and-gevent)

**Comment by skoczen** [comment]
@wohali thanks for the analysis!  Will dig into this, and get it sorted when my next block of will-focused cycles go around.   Always lovely to have better programmers than I improving the codebase!

-Steven

**Comment by wohali** [comment]
My pleasure. Debugging this was easier than writing my own framework from scratch :wink:

**Comment by skoczen** [comment]
This fix is going out as `v0.6.4` today.  @wohali, I've added you to AUTHORS based on your gh profile - please submit a PR if you'd like different attribution.

Also, if you or anyone else wants to do more digging into will's internals, it's very much welcome!  My strengths are in user-focused design, not capitol-P Programming. I'm sure there are more things like this lurking under the hood!

Thanks again for the fix.

**Comment by wohali** [comment]
My pleasure! That attribution is fine.

I have a plugin here that I've coded that fires off a secondary thread. That thread watches for events on a WebSocket, then acts based upon information that's provided. I'll try and get it published and perhaps it'll help others out who want the bot to act of their own accord, as opposed to always being triggered by a user asking it something first.

**Comment by wohali** [comment]
Oh and you can close this issue now! :)

**Comment by skoczen** [comment]
@wohali sounds great on all counts.  Out of curiosity, what's the advantage you're seeing of using a websocket over the webhook pattern?  Just latency/overhead?

Closing it up!

**Comment by wohali** [comment]
Hey @skoczen I'm afraid I bailed on this as the pricing for HipChat Server made it infeasible for me. If you'd still like my sample plugin code I'm happy to share.
