### ISSUE TITLE
Will Bot cannot handle responses from webhooks

### ISSUE THREAD

**Issue by dothak** [skoczen/will#79]
When trying to integrate will bot to respond to pagerduty webhook in chat, get this error (regardless of self.say() or self.reply())

I suspect it has something to do with the fact that will doesn't have a sender name or nick to respond to.

DEBUG    Event triggered: muc::xxxxx_chatroom@conf.hipchat.com::message
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/will/listener.py", line 153, in fn
    content = "@%s %s" % (msg.sender["nick"], content)
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by dothak** [comment]
@skoczen here is the error message.  I updated the bot and now it'll push the error message into the chat room.


MESSAGE:  {'xml': <Element '{jabber:client}message' at 0x7f10a9c7cf30>, 'sender': None, 'parent': None, 'stream': <will.main.WillBot object at 0x7f10ac125050>, '_index': 0, 'namespace': u'jabber:client', 'loaded_plugins': set(['html']), 'tag': u'{jabber:client}message', 'plugins': OrderedDict([(('html', u''), <html xmlns="http://jabber.org/protocol/xhtml-im"><body xmlns="http://www.w3.org/1999/xhtml">Incident <a href="https://xxxx.pagerduty.com/incidents/xxxx">20821</a> triggered by <a href="https://xxxx.pagerduty.com/services/xxxx">ZZZZZ</a> and assigned to <a href="https://xxxx.pagerduty.com/users/zzzz">John Doe</a> &amp; <a href="https://xxxx.pagerduty.com/users/xxxx">Jane Doe</a>: sample message.</body></html>)]), 'iterables': [], 'room': {u'xmpp_jid': u'76976_bot-testing-zz@conf.hipchat.com', u'name': u'bot-testing-zz', u'last_active': 1419016116, u'created': 1414864287, u'is_archived': False, u'topic': u'"herpaderpaherpaderp"', u'room_id': 939243, u'owner_user_id': 902007, u'is_private': True, u'guest_access_url': None}}
INFO     Starting new HTTPS connection (1): api.hipchat.com
DEBUG    RECV: <message from="76976_bot-testing-zz@conf.hipchat.com/jarvis bot" type="groupchat" mid="839c0754-69f8-4cf7-a260-e085d195cb86" to="76976_1376741@chat.hipchat.com/bot||proxy|pubproxy-e20.hipchat.com|5252" ts="1420215751.771990"><body>I ran into trouble running PDPlugin.trigger:

Traceback (most recent call last):
  File &quot;/home/ubuntu/.virtualenvs/jarvisbot/local/lib/python2.7/site-packages/will/listener.py&quot;, line 148, in fn
    listener[&quot;fn&quot;](*args, **kwargs)
  File &quot;/home/ubuntu/.virtualenvs/jarvisbot/local/lib/python2.7/site-packages/will/decorators.py&quot;, line 41, in wrapped_f
    f(*args, **kwargs)
  File &quot;/home/ubuntu/jarvisbot/jarvisbot/plugins/pagerduty.py&quot;, line 17, in trigger
    self.reply(message, &quot;triggered&quot;)
  File &quot;/home/ubuntu/.virtualenvs/jarvisbot/local/lib/python2.7/site-packages/will/plugin.py&quot;, line 72, in reply
    content = &quot;@%s %s&quot; % (message.sender[&quot;nick&quot;], content)
TypeError: &apos;NoneType&apos; object has no attribute &apos;__getitem__&apos;
</body><x xmlns="http://hipchat.com/protocol/muc#room"><type>system</type><notify>0</notify><color>red</color><message_format>text</message_format></x></message>

**Comment by dothak** [comment]
bump

**Comment by skoczen** [comment]
Hey, so I'm pretty slammed at the moment, so won't have time to get this sorted for a bit.

I also don't have your setup, so replicating's tough.  Best solution at the present is for you to trace it back in your local code - I'm pretty sure this should be a simple fix, with some conditionals around the nick substitution.  Oddly, I thought I added that in the latest release. 

In any case though, since all the source is open (and sitting in your virtualenv at `/home/ubuntu/.virtualenvs/jarvisbot/local/lib/python2.7/site-packages/will/listener.py`), I'd say if you have time, hop on checking into what's happening, test it, and send over a PR!

Thanks for your patience, and sorry that's the best I've got - will isn't actually my work job!

-Steven

**Comment by skoczen** [comment]
So, digging into this, the problem in your latest traceback is that you're using `self.reply`, which doesn't make sense for a webhook, since there's no user to reply to.

I'm adding more robust handling (will will now just output the message content, with a note that `.reply` was called without someone to reply to) in the next release, then closing this issue.  Please reopen if you still have this trouble!

**Comment by skoczen** [comment]
Released in [0.7.2](http://skoczen.github.io/will/improve/)!
