### ISSUE TITLE
How about having an open source plugin collection site?

### ISSUE THREAD

**Issue by woohgit** [skoczen/will#98]
I'm thinking about opening/creating a new site which would be the place for several will plugins. Maybe moving the by default disabled plugins to a separate plugin and make it available on a site would be a great idea.

For example the Lita bot has a plugin site https://www.lita.io/plugins which is pretty great.

We would just only need to implement a standard way to install and organise will plugins.

What do you think? I'll be pretty happy to unify and share my own plugins we use.

**Comment by PrideRage** [comment]
Personally I'd love to see that. Having to create a PR to get your Plugin published is just not the easiest way for many people I guess.
Maybe the collection site should be managed sorta like the PyPI. Let me explain:
Suppose it's like the plugin page that @woohgit presented, but you can also install these plugins directly from within will. So along with the run_will.py file, there could be a will_plugins.py file, and you could call it like
```bash
./will_plugins.py install NameOfPlugin
```
That would be, in my opinion, the most convenient way to do this for the average user.
Also, remove plugins like this maybe:
```bash
./will_plugins.py uninstall NameOfPlugin
```

@woohgit @skoczen What do you guys think?

**Comment by skoczen** [comment]
Hey @woohgit ,

Will aim to get a proper reply to this shortly (will see how the week shakes out,) but for the moment:

1. Thanks for raising this issue!
2. The current pattern is to submit any plugins you'd like other people to be able to use as PRs.   Folks can then enable/disable as they choose.
3. A plugin repo / install functionality is something that's been thought about a *lot*, and has thus far been decided against.  In fact, [frustration with that system was one of the reasons will was created](https://github.com/skoczen/will/issues/88#issuecomment-72205126).  

I try to always keep an open mind, but to me, there are lots of existing solutions out there if you want a  plugin-repo sort of bot (eek comes to mind).   As of right now, that's not the pattern for will. 

Keeping this a bit short (more later), but I did want to get a reply in before you invested a ton of time in it.  If you're still super-pro after reading this and the link above, I'd love to understand why.

Thanks,
-Steven

**Comment by woohgit** [comment]
Ok, I got your point.

You don't want to introduce new patterns to will and the current way is actually working. In this case I'll try to create basic will plugins and send PRs instead. Let's see how it works.

**Comment by skoczen** [comment]
@woohgit exactly.  Definitely willing to keep an open mind on this.  The thing I want to keep for bundled plugins is good, clear documentation, so people can easily see what's there.  For the moment, PRs seem like simplest way to me to achieve it.

@PrideRage - Re: pypi-like functionality.  Since will plugins are just python packages, you can actually already do that.  Just use pypi, and specify the package in config.  This lets you use pip, setuptools, and the whole python ecosystem for package management and dependency without having to roll our own.

If people *do* start making packages that way instead of as PRs to will (let's say they're big pieces of functionality, that we all agree don't belong in core), I'd be happy to start a simple `.md` file as part of the docs that maintains a list.

**Comment by dpoirier** [comment]
Using pypi sounds like a great idea. Why recreate what pypi already does pretty well?

**Comment by sivy** [comment]
:+1:
